POST http://localhost:8000/send_email HTTP/1.1
content-type: application/json

{
  "sender_name": "Collin Sparks",
  "sender_email": "cklsparks@gmail.com",
  "subject": "OMG",
  "body": "HUYNHY IS THA BEST HUNNY EVERE IN DA WROLD AND WE HAVE CUTE PUPPIES\n<3"
}

###

POST sparksie-api.vercel.app/send_email HTTP/1.1
content-type: application/json

{
  "sender_name": "Collin Sparks",
  "sender_email": "cklsparks@gmail.com",
  "subject": "OMG",
  "body": "HUYNHY IS THA BEST HUNNY EVERE IN DA WROLD AND WE HAVE CUTE PUPPIES\n<3"
}