POST http://localhost:8000/send_email HTTP/1.1
content-type: application/json

{
  "sender_name": "Collin Sparks",
  "sender_email": "cklsparks@gmail.com",
  "subject": "Not an important message",
  "body": "This is a very professional email which you are receiving"
}

###

POST sparksie-api.vercel.app/send_email HTTP/1.1
content-type: application/json

{
  "sender_name": "Collin Sparks",
  "sender_email": "cklsparks@gmail.com",
  "subject": "Did it work?",
  "body": "This is a test message which should be reaching me through the Vercel server"
}